# Python Probability
Use NumPy to create simulations and compute proportions for the following outcomes.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

In [11]:
import numpy as np
import pandas as pd


## Probability: Coin Flips and Die Rolls 

### 1. Four fair coin flips produce exactly three head

In [34]:
# simulate 1 thousand tests of four fair coin flips
tests =np.random.choice([0, 1], size=(1000,4))

# sums of all tests
test_sums =tests.sum(axis=0)

# proportion of tests that produced exactly three head
(test_sums==1).mean()

0.0

### 2. Four biased coin flips with P(H) = 0.7 produce exactly two head

In [33]:
# simulate 1 thousand tests of four biased coin flips
# hint: use np.random.choice()
tests =np.random.choice([0, 1], size=(1000,4), p=[0.7, 0.3])
# sums of all tests
test_sums =tests.sum(axis=1)

# proportion of tests that produced exactly two head
(test_sums==2).mean()

[[0 0 1 0]
 [1 1 0 0]
 [0 0 1 0]
 ...
 [0 0 1 0]
 [0 1 1 1]
 [0 1 0 0]]


0.262

### 3. A die rolls an odd number

In [8]:
# simulate 1 thousand tests of one die roll
tests =np.random.choice(np.arange(1, 7), size=int(1000))

# proportion of tests that produced an odd number
(tests % 2 != 0).mean()

0.473

### 4. Two dice roll a double

In [10]:
# simulate the first thousand die rolls
first = np.random.choice(np.arange(1, 7), size=int(1000))

# simulate the second thousand die rolls
second =np.random.choice(np.arange(1, 7), size=int(1000))

# proportion of tests where the 1st die is greater than the 2nd rolled
(first>second).mean()

0.387

## Conditional Probability & Bayes Rule

In [13]:
# load dataset
df=pd.read_csv("hyperthyrodism_test_data.csv")

In [14]:
df.head(10)

patient_id test_result  has_hyperthyrodism
0       79452    Negative               False
1       81667    Positive                True
2       76297    Negative               False
3       36593    Negative               False
4       53717    Negative               False
5       67134    Negative               False
6       40436    Negative               False
7       77872    Positive                True
8       78761    Positive                True
9       71212    Negative               False

### P(hyperthyrodism|positive)

In [22]:
# What proportion of patients who tested positive has hyperthyrodism?
df.query("test_result=='Positive'") ["has_hyperthyrodism"].mean()

0.34282178217821785

### P(~hyperthyrodism|positive)

In [23]:
# What proportion of patients who tested positive doesn't have hyperthyrodism?
1-df.query("test_result=='Positive'") ["has_hyperthyrodism"].mean()

0.6571782178217822

### P(hyperthyrodism|negative)

In [24]:
# What proportion of patients who tested negative has hyperthyrodism?
df.query("test_result=='Negative'") ["has_hyperthyrodism"].mean()

0.013770180436847104

### P(~hyperthyrodism|negative)

In [25]:
# What proportion of patients who tested negative doesn't have hyperthyrodism?
1-df.query("test_result=='Negative'") ["has_hyperthyrodism"].mean()

0.9862298195631529

In [31]:
(df.query("test_result=='Negative'") ["has_hyperthyrodism"]==False).mean()

0.9862298195631529